_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.05015394512911528
clustering_method:
    value: hdbscan
dbscan_min_samples:
    value: 3
entropy_threshold_high:
    value: 5.455076944028102
entropy_threshold_low:
    value: 0.17070049067450693
eps_max:
    value: 3.7607734339895296
eps_min:
    value: 0.1630134600175729
eps_steps:
    value: 30
hdbscan_cluster_selection_epsilon:
    value: 0.2457204405634147
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 10
hdbscan_min_samples:
    value: 1
max_prompt_length:
    value: 150
min_prompt_length:
    value: 10
n_prompts:
    value: 1000
sparsity_max:
    value: 0.860007905167924
sparsity_min:
    value: 0.12934454495584857
umap_metric:
    value: cosine
umap_min_dist:
    value: 0.1
umap_n_components:
    value: 25
umap_n_neighbors:
    value: 15
use_umap_preprocessing:
    value: true
