_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.1104370204274021
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 1
entropy_threshold_high:
    value: 5.752354918006015
entropy_threshold_low:
    value: 0.27319928696584694
eps_max:
    value: 3.7921284629052407
eps_min:
    value: 0.16871838848621634
eps_steps:
    value: 20
hdbscan_cluster_selection_epsilon:
    value: 0.1286883471142602
hdbscan_metric:
    value: manhattan
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 5
max_prompt_length:
    value: 50
min_prompt_length:
    value: 10
n_prompts:
    value: 1000
sparsity_max:
    value: 0.8962154575861442
sparsity_min:
    value: 0.09832557696816374
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0.5
umap_n_components:
    value: 100
umap_n_neighbors:
    value: 30
use_pipeline:
    value: true
use_umap_preprocessing:
    value: true
