_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.08260991693488025
clustering_method:
    value: hdbscan
dbscan_min_samples:
    value: 5
entropy_threshold_high:
    value: 5.864964083702571
entropy_threshold_low:
    value: 0.16069921814244031
eps_max:
    value: 4.633480477887974
eps_min:
    value: 0.0702291225907213
eps_steps:
    value: 30
hdbscan_cluster_selection_epsilon:
    value: 0.28144537301270206
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 10
hdbscan_min_samples:
    value: 2
max_prompt_length:
    value: 50
min_prompt_length:
    value: 30
n_prompts:
    value: 1000
sparsity_max:
    value: 0.9811451698983632
sparsity_min:
    value: 0.18103754956678203
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0
umap_n_components:
    value: 50
umap_n_neighbors:
    value: 30
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
