wandb_version: 1

activation_threshold:
  value: 0.13920833330492569
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 6.523765962567076
entropy_threshold_low:
  value: 0.22741581781285536
eps_max:
  value: 5.5638635483257515
eps_min:
  value: 0.052569648065092026
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.3868853450866638
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 300
sparsity_max:
  value: 0.8794096249201847
sparsity_min:
  value: 0.10138767472557522
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
