wandb_version: 1

activation_threshold:
  value: 0.05790126493981648
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 5.204680785411524
entropy_threshold_low:
  value: 0.15917080812694928
eps_max:
  value: 5.122237504030543
eps_min:
  value: 0.19377828700970065
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.07816820987907891
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 10
n_prompts:
  value: 30
sparsity_max:
  value: 0.8297289503517574
sparsity_min:
  value: 0.1089882749654262
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
