wandb_version: 1

activation_threshold:
  value: 0.1343547499671345
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 3.303286562507782
entropy_threshold_low:
  value: 0.2687363190580887
eps_max:
  value: 6.748152204183892
eps_min:
  value: 0.18301881540032375
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.473819662388304
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 300
sparsity_max:
  value: 0.95150644629865
sparsity_min:
  value: 0.1521042215908559
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
