wandb_version: 1

activation_threshold:
  value: 0.14164505435106528
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 6.3077005953672325
entropy_threshold_low:
  value: 0.24788049317424135
eps_max:
  value: 4.516174793126634
eps_min:
  value: 0.06458388037537775
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.1087210208448856
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 10
sparsity_max:
  value: 0.940332502629896
sparsity_min:
  value: 0.05625658548775861
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
