wandb_version: 1

activation_threshold:
  value: 0.14758634346835525
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 3.622969604030522
entropy_threshold_low:
  value: 0.13462870347265113
eps_max:
  value: 5.844873654513364
eps_min:
  value: 0.24376887811790365
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.3331856791806173
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 2
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 100
min_prompt_length:
  value: 20
n_prompts:
  value: 1000
sparsity_max:
  value: 0.8561748426528655
sparsity_min:
  value: 0.05644590936866976
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
