wandb_version: 1

activation_threshold:
  value: 0.10350917138165278
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 5.634483651534502
entropy_threshold_low:
  value: 0.30253754099313357
eps_max:
  value: 3.348559534258829
eps_min:
  value: 0.18492872014386505
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.07919071788630938
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 20
n_prompts:
  value: 30
sparsity_max:
  value: 0.8738406404883231
sparsity_min:
  value: 0.10225097363054586
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
