wandb_version: 1

activation_threshold:
  value: 0.16240193503535638
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 4.317020393461718
entropy_threshold_low:
  value: 0.395000182472136
eps_max:
  value: 5.036223849799247
eps_min:
  value: 0.159754731859983
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.21060189877417831
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.8131542692954469
sparsity_min:
  value: 0.06887354698068128
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
