wandb_version: 1

activation_threshold:
  value: 0.09671338922458252
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 4.4677904633361
entropy_threshold_low:
  value: 0.33384600138032994
eps_max:
  value: 3.16537563827439
eps_min:
  value: 0.28743670734194887
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.0434909074249622
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 30
sparsity_max:
  value: 0.9731753876166948
sparsity_min:
  value: 0.07975431328301631
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
