wandb_version: 1

activation_threshold:
  value: 0.12134207311290188
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 6.879069108178539
entropy_threshold_low:
  value: 0.3016947374772512
eps_max:
  value: 4.327396019907326
eps_min:
  value: 0.07740526581182706
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.1642873678483095
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 10
sparsity_max:
  value: 0.8517714986416487
sparsity_min:
  value: 0.05347421062300584
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
