wandb_version: 1

activation_threshold:
  value: 0.06332188613382486
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 4.083826471729362
entropy_threshold_low:
  value: 0.1929335079548653
eps_max:
  value: 4.731406943679982
eps_min:
  value: 0.11165600436001576
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.2273946496757485
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 100
sparsity_max:
  value: 0.8071813054597238
sparsity_min:
  value: 0.0771289687983733
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
