wandb_version: 1

activation_threshold:
  value: 0.08103745160821006
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 6.251742850924819
entropy_threshold_low:
  value: 0.4972564963270937
eps_max:
  value: 6.74567178099474
eps_min:
  value: 0.06888415688330991
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.13537059373282068
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.9604977154892452
sparsity_min:
  value: 0.16392804233593244
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
