wandb_version: 1

activation_threshold:
  value: 0.13115905308429832
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 4.289465604413044
entropy_threshold_low:
  value: 0.14057658749523064
eps_max:
  value: 3.319878354356544
eps_min:
  value: 0.12043501702495558
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.05905489320202578
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 30
sparsity_max:
  value: 0.90492478741575
sparsity_min:
  value: 0.0580855278425633
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
