wandb_version: 1

activation_threshold:
  value: 0.1431033140059863
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.071789896985477
entropy_threshold_low:
  value: 0.33220581249413894
eps_max:
  value: 3.076120933077494
eps_min:
  value: 0.09816525631970778
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.44343677246857827
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 10
sparsity_max:
  value: 0.9488680907707864
sparsity_min:
  value: 0.051074450603968785
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
