wandb_version: 1

activation_threshold:
  value: 0.096294572653205
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.709035928809411
entropy_threshold_low:
  value: 0.45882472320853984
eps_max:
  value: 4.8580728413019365
eps_min:
  value: 0.06651539249973536
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.4053803993604552
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 10
n_prompts:
  value: 30
sparsity_max:
  value: 0.8820617711453391
sparsity_min:
  value: 0.07100721625135491
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
