wandb_version: 1

activation_threshold:
  value: 0.138033759609912
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 4.5853576516135846
entropy_threshold_low:
  value: 0.1966897463010888
eps_max:
  value: 4.602082125654824
eps_min:
  value: 0.10569980553124052
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.08114343024132747
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 100
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.9053724313104788
sparsity_min:
  value: 0.06818347013295317
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
