wandb_version: 1

activation_threshold:
  value: 0.16766401435312994
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 5.680385766107653
entropy_threshold_low:
  value: 0.26391791505195894
eps_max:
  value: 3.802641476915838
eps_min:
  value: 0.061401796123627186
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.06858912126252359
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 100
sparsity_max:
  value: 0.8990987636790596
sparsity_min:
  value: 0.05685266239083025
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
