wandb_version: 1

activation_threshold:
  value: 0.07384209997869107
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 4.0971007797772545
entropy_threshold_low:
  value: 0.3733001261586063
eps_max:
  value: 5.738101599470154
eps_min:
  value: 0.126073348586272
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.2672000209769686
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 2
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 1000
sparsity_max:
  value: 0.9466502289478128
sparsity_min:
  value: 0.06739665559299833
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
