wandb_version: 1

activation_threshold:
  value: 0.19867750314277569
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 6.443332111859156
entropy_threshold_low:
  value: 0.4581966383376801
eps_max:
  value: 3.635094682522544
eps_min:
  value: 0.23056442348741943
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.13469510325439776
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 10
sparsity_max:
  value: 0.8434283851450862
sparsity_min:
  value: 0.10914012118767548
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
