wandb_version: 1

activation_threshold:
  value: 0.19104651678843
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 4.452773363235417
entropy_threshold_low:
  value: 0.10485531603733196
eps_max:
  value: 4.3634097372215415
eps_min:
  value: 0.16123474654806708
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.29307387494885634
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 2
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 30
n_prompts:
  value: 1000
sparsity_max:
  value: 0.9040350302385024
sparsity_min:
  value: 0.16768514583995842
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
