wandb_version: 1

activation_threshold:
  value: 0.05824097343336914
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.619052596819851
entropy_threshold_low:
  value: 0.21320208519615
eps_max:
  value: 3.4259165110894685
eps_min:
  value: 0.23132061372465976
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.01654912842652445
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 100
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.832632905585437
sparsity_min:
  value: 0.12499329928115678
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
