wandb_version: 1

activation_threshold:
  value: 0.1673451268091029
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 4.91051539721021
entropy_threshold_low:
  value: 0.2530336098407676
eps_max:
  value: 4.923952430537248
eps_min:
  value: 0.05826312123865114
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.27933632765543925
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 10
n_prompts:
  value: 30
sparsity_max:
  value: 0.9527378611009588
sparsity_min:
  value: 0.05438678752053425
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
