wandb_version: 1

activation_threshold:
  value: 0.15599650258020695
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 6.948880096808386
entropy_threshold_low:
  value: 0.3983297223164922
eps_max:
  value: 6.264224654903204
eps_min:
  value: 0.07346149220189431
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.23747478621079748
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 150
min_prompt_length:
  value: 30
n_prompts:
  value: 30
sparsity_max:
  value: 0.8934821381147213
sparsity_min:
  value: 0.062170997153166055
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
