wandb_version: 1

activation_threshold:
  value: 0.0910752397844198
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.643808352834038
entropy_threshold_low:
  value: 0.4337991465372708
eps_max:
  value: 6.009323503230266
eps_min:
  value: 0.20970804902212353
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.02983209249852453
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 10
n_prompts:
  value: 10
sparsity_max:
  value: 0.8307362844719455
sparsity_min:
  value: 0.06071987529144361
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
