wandb_version: 1

activation_threshold:
  value: 0.07362677224157403
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 5.582998511749027
entropy_threshold_low:
  value: 0.4731213555710361
eps_max:
  value: 4.2403425185035175
eps_min:
  value: 0.14376600922134664
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.12325025375028686
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 150
min_prompt_length:
  value: 20
n_prompts:
  value: 30
sparsity_max:
  value: 0.91555558697647
sparsity_min:
  value: 0.13003808693828783
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
