wandb_version: 1

activation_threshold:
  value: 0.1094556209798267
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.669523452420112
entropy_threshold_low:
  value: 0.1807854844989768
eps_max:
  value: 4.205075838935766
eps_min:
  value: 0.08602192666592813
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.2296117041165383
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 100
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.8905100040545385
sparsity_min:
  value: 0.06526338802268805
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
