_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.0904541777823102
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 3
entropy_threshold_high:
    value: 4.506234902473517
entropy_threshold_low:
    value: 0.3936816512560702
eps_max:
    value: 5.873147778720021
eps_min:
    value: 0.0954631487496347
eps_steps:
    value: 40
hdbscan_cluster_selection_epsilon:
    value: 0.2600471304039209
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 2
max_prompt_length:
    value: 100
min_prompt_length:
    value: 20
n_prompts:
    value: 10
sparsity_max:
    value: 0.9004183637605805
sparsity_min:
    value: 0.17479259020702595
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0.1
umap_n_components:
    value: 25
umap_n_neighbors:
    value: 5
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
