_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.06459180174657256
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 2
entropy_threshold_high:
    value: 6.178127087905693
entropy_threshold_low:
    value: 0.3738178685185613
eps_max:
    value: 3.584182318388845
eps_min:
    value: 0.0813828182085611
eps_steps:
    value: 40
hdbscan_cluster_selection_epsilon:
    value: 0.1813225778899044
hdbscan_metric:
    value: manhattan
hdbscan_min_cluster_size:
    value: 10
hdbscan_min_samples:
    value: 1
max_prompt_length:
    value: 50
min_prompt_length:
    value: 30
n_prompts:
    value: 10
sparsity_max:
    value: 0.8507702614491133
sparsity_min:
    value: 0.10340667487311056
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0.1
umap_n_components:
    value: 100
umap_n_neighbors:
    value: 5
use_pipeline:
    value: true
use_umap_preprocessing:
    value: true
