_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.1729321797204727
clustering_method:
    value: hdbscan
dbscan_min_samples:
    value: 3
entropy_threshold_high:
    value: 4.260829576811567
entropy_threshold_low:
    value: 0.31890956842708595
eps_max:
    value: 3.062511618077334
eps_min:
    value: 0.12958776441894004
eps_steps:
    value: 30
hdbscan_cluster_selection_epsilon:
    value: 0.393248316368794
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 10
hdbscan_min_samples:
    value: 1
max_prompt_length:
    value: 150
min_prompt_length:
    value: 30
n_prompts:
    value: 1000
sparsity_max:
    value: 0.8368380949497431
sparsity_min:
    value: 0.1093396250209392
umap_metric:
    value: cosine
umap_min_dist:
    value: 0.5
umap_n_components:
    value: 25
umap_n_neighbors:
    value: 5
use_pipeline:
    value: true
use_umap_preprocessing:
    value: true
