_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.06357660635927882
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 5
entropy_threshold_high:
    value: 6.993997903955803
entropy_threshold_low:
    value: 0.3745524878896576
eps_max:
    value: 3.4497732612187613
eps_min:
    value: 0.28178497758517046
eps_steps:
    value: 40
hdbscan_cluster_selection_epsilon:
    value: 0.26824278149963265
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 2
max_prompt_length:
    value: 150
min_prompt_length:
    value: 10
n_prompts:
    value: 30
sparsity_max:
    value: 0.8473081771385389
sparsity_min:
    value: 0.15133378322011248
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0
umap_n_components:
    value: 100
umap_n_neighbors:
    value: 30
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
