_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.052216421245451616
clustering_method:
    value: hdbscan
dbscan_min_samples:
    value: 3
entropy_threshold_high:
    value: 4.605388421406642
entropy_threshold_low:
    value: 0.2139017780349001
eps_max:
    value: 3.0605725600061686
eps_min:
    value: 0.07287341660887516
eps_steps:
    value: 30
hdbscan_cluster_selection_epsilon:
    value: 0.25075837958576
hdbscan_metric:
    value: manhattan
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 1
max_prompt_length:
    value: 100
min_prompt_length:
    value: 10
n_prompts:
    value: 100
sparsity_max:
    value: 0.8123074203455625
sparsity_min:
    value: 0.1902458393649465
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0
umap_n_components:
    value: 50
umap_n_neighbors:
    value: 15
use_pipeline:
    value: true
use_umap_preprocessing:
    value: true
