wandb_version: 1

activation_threshold:
  value: 0.06029205490788382
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.106736129761346
entropy_threshold_low:
  value: 0.412602134220368
eps_max:
  value: 4.857227918102344
eps_min:
  value: 0.08624554714948075
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.26892758219629276
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 10
n_prompts:
  value: 100
sparsity_max:
  value: 0.8367601903355859
sparsity_min:
  value: 0.08930970111150559
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
