wandb_version: 1

activation_threshold:
  value: 0.0603121391601974
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 5.556265882679739
entropy_threshold_low:
  value: 0.12386438254477992
eps_max:
  value: 3.711220331120357
eps_min:
  value: 0.09814351077036625
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.006185857777583736
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 10
n_prompts:
  value: 10
sparsity_max:
  value: 0.8435811272957977
sparsity_min:
  value: 0.08463489565133647
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
