wandb_version: 1

activation_threshold:
  value: 0.11246183587613798
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 6.103788926459524
entropy_threshold_low:
  value: 0.3708021131201886
eps_max:
  value: 3.035676902311537
eps_min:
  value: 0.09889645329117272
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.17436694092500732
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 100
min_prompt_length:
  value: 10
n_prompts:
  value: 1000
sparsity_max:
  value: 0.8944306134565911
sparsity_min:
  value: 0.12849654160862234
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
