wandb_version: 1

activation_threshold:
  value: 0.14567061755996363
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.880156824887068
entropy_threshold_low:
  value: 0.3446525818826002
eps_max:
  value: 4.168064609084829
eps_min:
  value: 0.20773526223203043
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.08280552925804263
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 100
min_prompt_length:
  value: 20
n_prompts:
  value: 10
sparsity_max:
  value: 0.8150400213491465
sparsity_min:
  value: 0.1684393328611904
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
