wandb_version: 1

activation_threshold:
  value: 0.08716511882981234
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 5.0465606066903455
entropy_threshold_low:
  value: 0.12408389661572104
eps_max:
  value: 3.608034707361176
eps_min:
  value: 0.11336828353422096
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.04385919802566929
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 10
n_prompts:
  value: 300
sparsity_max:
  value: 0.9429590135391974
sparsity_min:
  value: 0.18438281724626793
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
