wandb_version: 1

activation_threshold:
  value: 0.07789689622597937
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.049400204796527
entropy_threshold_low:
  value: 0.3367061205623184
eps_max:
  value: 3.965992565002708
eps_min:
  value: 0.08169980202814735
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.4792020623680121
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 100
sparsity_max:
  value: 0.8481369303380314
sparsity_min:
  value: 0.10383119516053466
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
