wandb_version: 1

activation_threshold:
  value: 0.1151231788531502
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 6.166247024432888
entropy_threshold_low:
  value: 0.18739559630340255
eps_max:
  value: 3.602252898221349
eps_min:
  value: 0.0754908245393265
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.18050663074690895
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 100
min_prompt_length:
  value: 10
n_prompts:
  value: 100
sparsity_max:
  value: 0.8771881179051516
sparsity_min:
  value: 0.1966973530819428
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
