wandb_version: 1

activation_threshold:
  value: 0.10122179494783826
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 5.413236665713111
entropy_threshold_low:
  value: 0.3302529207038059
eps_max:
  value: 4.028413650069506
eps_min:
  value: 0.16047375556847632
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.33732396707460693
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 2
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 300
sparsity_max:
  value: 0.9153852047955352
sparsity_min:
  value: 0.18663232695997825
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
