wandb_version: 1

activation_threshold:
  value: 0.10384752775961432
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 5.771416305707319
entropy_threshold_low:
  value: 0.13363809853444025
eps_max:
  value: 4.605451990061625
eps_min:
  value: 0.2482295468669676
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.3112687519313885
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 20
n_prompts:
  value: 100
sparsity_max:
  value: 0.9306182781541807
sparsity_min:
  value: 0.16558274158158454
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
