wandb_version: 1

activation_threshold:
  value: 0.1451538565506957
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 5
entropy_threshold_high:
  value: 6.524232012257329
entropy_threshold_low:
  value: 0.26450232346812697
eps_max:
  value: 3.886480687689344
eps_min:
  value: 0.1422061543696691
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.3937425021375659
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 10
n_prompts:
  value: 300
sparsity_max:
  value: 0.8276067059272373
sparsity_min:
  value: 0.1969388306107699
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
