wandb_version: 1

activation_threshold:
  value: 0.08082973875351417
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.623204285728251
entropy_threshold_low:
  value: 0.36176504400118314
eps_max:
  value: 3.538176695192887
eps_min:
  value: 0.1582958043531263
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.25486242516216423
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 20
n_prompts:
  value: 30
sparsity_max:
  value: 0.9262842334457236
sparsity_min:
  value: 0.10923434185347183
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
