wandb_version: 1

activation_threshold:
  value: 0.0771954997275278
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 4.72557959496788
entropy_threshold_low:
  value: 0.175239939225487
eps_max:
  value: 3.054095438851016
eps_min:
  value: 0.12139519837178066
eps_steps:
  value: 20
hdbscan_cluster_selection_epsilon:
  value: 0.08125336948540607
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 50
min_prompt_length:
  value: 10
n_prompts:
  value: 10
sparsity_max:
  value: 0.907711362280872
sparsity_min:
  value: 0.19772522086990457
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
