wandb_version: 1

activation_threshold:
  value: 0.12342360607501893
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 5.24967607832688
entropy_threshold_low:
  value: 0.1351635476699221
eps_max:
  value: 3.3188704117815613
eps_min:
  value: 0.25163200801956
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.3770770081706692
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 100
min_prompt_length:
  value: 10
n_prompts:
  value: 300
sparsity_max:
  value: 0.8494901898140768
sparsity_min:
  value: 0.12241629234023756
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
