wandb_version: 1

activation_threshold:
  value: 0.055509975015107176
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.87802991207537
entropy_threshold_low:
  value: 0.13573023140704654
eps_max:
  value: 4.296765363536578
eps_min:
  value: 0.22069556009328595
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.30388607131611445
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 20
n_prompts:
  value: 10
sparsity_max:
  value: 0.8524451402442668
sparsity_min:
  value: 0.1806057400948931
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
