wandb_version: 1

activation_threshold:
  value: 0.11738805310775956
clustering_method:
  value: hdbscan
dbscan_min_samples:
  value: 1
entropy_threshold_high:
  value: 3.672236597160993
entropy_threshold_low:
  value: 0.4149859251076031
eps_max:
  value: 4.887778392345969
eps_min:
  value: 0.2502852700807054
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.08230955326989237
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 2
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 1000
sparsity_max:
  value: 0.9315104794105636
sparsity_min:
  value: 0.0934154378225976
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 5
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
