wandb_version: 1

activation_threshold:
  value: 0.06819324038503463
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 5.127733705516402
entropy_threshold_low:
  value: 0.4161995167339001
eps_max:
  value: 6.57034863116013
eps_min:
  value: 0.11307845575375217
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.360604192362268
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 1
max_prompt_length:
  value: 150
min_prompt_length:
  value: 10
n_prompts:
  value: 100
sparsity_max:
  value: 0.8926046063702445
sparsity_min:
  value: 0.06215055259004412
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
