wandb_version: 1

activation_threshold:
  value: 0.09314958781591716
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 5.7108045754928725
entropy_threshold_low:
  value: 0.2251173791889549
eps_max:
  value: 3.365993255682405
eps_min:
  value: 0.1963095186118584
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.09504676904502868
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 10
hdbscan_min_samples:
  value: 2
max_prompt_length:
  value: 50
min_prompt_length:
  value: 30
n_prompts:
  value: 10
sparsity_max:
  value: 0.9084458455201042
sparsity_min:
  value: 0.0916468873620833
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
