_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.1087968851377979
clustering_method:
    value: hdbscan
dbscan_min_samples:
    value: 1
entropy_threshold_high:
    value: 3.493578589333609
entropy_threshold_low:
    value: 0.40858841474783625
eps_max:
    value: 3.1383061493201643
eps_min:
    value: 0.29942335467240105
eps_steps:
    value: 30
hdbscan_cluster_selection_epsilon:
    value: 0.4630886973111928
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 2
hdbscan_min_samples:
    value: 5
max_prompt_length:
    value: 150
min_prompt_length:
    value: 30
n_prompts:
    value: 100
sparsity_max:
    value: 0.9357489551060534
sparsity_min:
    value: 0.19773525662136637
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0
umap_n_components:
    value: 50
umap_n_neighbors:
    value: 30
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
