wandb_version: 1

activation_threshold:
  value: 0.15807508702245757
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 4.425106220269442
entropy_threshold_low:
  value: 0.16496997008723047
eps_max:
  value: 6.740565082459171
eps_min:
  value: 0.13164886050414187
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.492895046446764
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 50
min_prompt_length:
  value: 20
n_prompts:
  value: 30
sparsity_max:
  value: 0.9841118759519434
sparsity_min:
  value: 0.16425056495197302
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 50
umap_n_neighbors:
  value: 15
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
