wandb_version: 1

activation_threshold:
  value: 0.15230864714876757
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 2
entropy_threshold_high:
  value: 6.663001849145182
entropy_threshold_low:
  value: 0.4062131735890489
eps_max:
  value: 5.084317265983074
eps_min:
  value: 0.1578228142393273
eps_steps:
  value: 30
hdbscan_cluster_selection_epsilon:
  value: 0.4161698338598987
hdbscan_metric:
  value: manhattan
hdbscan_min_cluster_size:
  value: 5
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 50
min_prompt_length:
  value: 10
n_prompts:
  value: 100
sparsity_max:
  value: 0.8222294318288125
sparsity_min:
  value: 0.15480285599955945
umap_metric:
  value: cosine
umap_min_dist:
  value: 0.1
umap_n_components:
  value: 100
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: true
