wandb_version: 1

activation_threshold:
  value: 0.1562781323157601
clustering_method:
  value: dbscan
dbscan_min_samples:
  value: 3
entropy_threshold_high:
  value: 6.018591936333225
entropy_threshold_low:
  value: 0.14113969430147907
eps_max:
  value: 5.861721894246129
eps_min:
  value: 0.2925633237690388
eps_steps:
  value: 40
hdbscan_cluster_selection_epsilon:
  value: 0.4854052916085768
hdbscan_metric:
  value: euclidean
hdbscan_min_cluster_size:
  value: 20
hdbscan_min_samples:
  value: 5
max_prompt_length:
  value: 150
min_prompt_length:
  value: 10
n_prompts:
  value: 300
sparsity_max:
  value: 0.8177092631391616
sparsity_min:
  value: 0.1465638809880707
umap_metric:
  value: euclidean
umap_min_dist:
  value: 0.5
umap_n_components:
  value: 25
umap_n_neighbors:
  value: 30
use_pipeline:
  value: true
use_umap_preprocessing:
  value: false
