_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.13522275835495934
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 1
entropy_threshold_high:
    value: 5.012470246623763
entropy_threshold_low:
    value: 0.3325876303398912
eps_max:
    value: 3.7286165224207544
eps_min:
    value: 0.19358123778576375
eps_steps:
    value: 40
hdbscan_cluster_selection_epsilon:
    value: 0.2127716504278866
hdbscan_metric:
    value: manhattan
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 2
max_prompt_length:
    value: 50
min_prompt_length:
    value: 20
n_prompts:
    value: 10
sparsity_max:
    value: 0.9000387783661676
sparsity_min:
    value: 0.12319194576370472
umap_metric:
    value: euclidean
umap_min_dist:
    value: 0.1
umap_n_components:
    value: 100
umap_n_neighbors:
    value: 15
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
