_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.16115092964855524
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 3
entropy_threshold_high:
    value: 4.762531138263032
entropy_threshold_low:
    value: 0.4839711675373951
eps_max:
    value: 5.778991295181166
eps_min:
    value: 0.09512608075406452
eps_steps:
    value: 20
hdbscan_cluster_selection_epsilon:
    value: 0.4926124889499056
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 10
hdbscan_min_samples:
    value: 5
max_prompt_length:
    value: 150
min_prompt_length:
    value: 30
n_prompts:
    value: 30
sparsity_max:
    value: 0.9629297470843694
sparsity_min:
    value: 0.06253062540000626
umap_metric:
    value: cosine
umap_min_dist:
    value: 0
umap_n_components:
    value: 50
umap_n_neighbors:
    value: 15
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
