_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
activation_threshold:
    value: 0.10427703593414094
clustering_method:
    value: dbscan
dbscan_min_samples:
    value: 2
entropy_threshold_high:
    value: 3.2902583611262477
entropy_threshold_low:
    value: 0.3600593600309402
eps_max:
    value: 6.801677328062257
eps_min:
    value: 0.27814305443928283
eps_steps:
    value: 40
hdbscan_cluster_selection_epsilon:
    value: 0.03958149204963157
hdbscan_metric:
    value: euclidean
hdbscan_min_cluster_size:
    value: 20
hdbscan_min_samples:
    value: 1
max_prompt_length:
    value: 100
min_prompt_length:
    value: 30
n_prompts:
    value: 100
sparsity_max:
    value: 0.8811273960572089
sparsity_min:
    value: 0.11235540264747264
umap_metric:
    value: cosine
umap_min_dist:
    value: 0.1
umap_n_components:
    value: 25
umap_n_neighbors:
    value: 5
use_pipeline:
    value: true
use_umap_preprocessing:
    value: false
